# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a52a3e3fcf98ba62b813ae98d42d503afd7712ea7362ed352b068ec358060e00d0e4d514e8979ae5c5d8bf6197c6ea7daacd301446f84487e9726a48278b219

test:
  secret_key_base: ffa42cb65cf8bc57df6a717b78d9e79fd2597f222b585a8586ed4b8ef74ee3f6b242abdf7266e4a1fdffddb559582c49c0c052bb3f33ce7c348e666ab48845cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
